### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by SaphiLC** [Lazer-Database/Lazer-Database#41]
How performant is it with a big amount of records? (1M or less for example) or its only for small projects?

thanks

**Comment by Greg0** [comment]
There is no benchmarks yet, but I designed it rather for small systems. Now @anant-svc is project maintainer

**Comment by anant-svc** [comment]
@shamuel22 
As all know **Lazer-Database** stores data in JSON string files so it depends on server configuration like PHP version, RAM, Inodes size, Linux 64-bit preferred.
This is for mid-level projects though it depends on AREA you will use in your projects.

Lastly there is no limitation on size of JSON string so **Lazer-Database** will works faster to get data and save data is bit slower for large data only.

**Comment by anant-svc** [comment]
@SaphiLC 
As all know **Lazer-Database** stores data in JSON string files so it depends on server configuration like PHP version, RAM, Inodes size, Linux 64-bit preferred.
This is for mid-level projects though it depends on AREA you will use in your projects.

Lastly there is no limitation on size of JSON string so **Lazer-Database** will works faster to get data and save data is bit slower for large data only.

**Comment by anant-svc** [comment]
@SaphiLC I have ported to PHP 7. Check this page: https://github.com/Lazer-Database/Lazer-Database/issues/42#issuecomment-650882035
