### ISSUE TITLE
Performance update

### ISSUE THREAD

**Issue by shamuel22** [Lazer-Database/Lazer-Database#42]
Hi  @anant-svc ! Do you plan to make updates to this package in the future to improve performance and memory consumption?

**Comment by shamuel22** [comment]
Great! Data encryption could give an extra advantage to this, I was testing with AES including the key as password.  I'm thinking of developing a platform base on Lazer-Database in NodeJs with control panel to Noob users. Let me know when the update is ready

**Comment by anant-svc** [comment]
Currently working on php7 porting and next is LazerDatabase adapter class for WordPress

**Comment by otengkwame** [comment]
I'm really waiting looking forward to the php7 port

**Comment by anant-svc** [comment]
Thanks for keeping me motivated and will release the php7 port soon. Whoever wants it then give thumbs up to this message.

**Comment by anant-svc** [comment]
@Greg0 @shamuel22 @otengkwame Here is the PHP 7 port commit here and let me know your suggestions:
https://github.com/anant-svc/Lazer-Database/commit/fbee5977618160d697daed677f0ae80f06bc4dd4

This supports PHP versions: 7.0, 7.1, 7.2, 7.3, and 7.4
Deprecates: PHP 5.6 and older versions

**Comment by ananth-iyer** [comment]
@otengkwame Hello, how is the latest version doing.

**Comment by anant-svc** [comment]
@otengkwame and all,
Hello, how is the latest version performing?
