### ISSUE TITLE
Creating tables and Saving Data return null

### ISSUE THREAD

**Issue by otengkwame** [Lazer-Database/Lazer-Database#66]
Let me quickly point this out. I know it is not an error but it will help if you can get the state whether table was created or table data was saved. 

It returns null on both. So in my implementation I just had to check if what I save exists then I return true. 

This is an example for checking if the data I currently saved exists. 

```php 
public static function exists($table_name, '$key, $value) 
{
                $exists = JsonDB::table($table_name)->where($key, '=', $value)->find();
		return ($exists->$key === $value) ? true : false; 
}
```

**Comment by anant-svc** [comment]
It is intended to return null by create table and saving data method. You can extend the `Database` class and create a new method to check data. Then used it in your application.

For saving data, you get the last saved id by `$table->lastId()`. Please check here: https://github.com/Lazer-Database/Lazer-Database/blob/master/tests/src/Classes/DatabaseTest.php#L398

**Comment by otengkwame** [comment]
@anant-svc  Thanks a lot for the reply. It has really helped. It seems I get it now.
