### ISSUE TITLE
Is there a way to add field to existing database

### ISSUE THREAD

**Issue by mitmelon** [Lazer-Database/Lazer-Database#74]
Am looking for a way to add field name to existing database... Please do you have a method for this in the project?

**Comment by anant-svc** [comment]
Yes, check - addFields() - append new fields into existing table
Here - https://github.com/Lazer-Database/Lazer-Database

**Comment by mitmelon** [comment]
Okay thank you... Got it solved...

**Comment by anant-svc** [comment]
@mitmelon  Check out Tool discuss for news - https://github.com/Lazer-Database/Lazer-Database/discussions/71
